### ISSUE TITLE
Broken external link

### ISSUE THREAD

**Issue by abdessalamb98** [twanmulder/thats-an-egg-blog#1]
In https://github.com/twanmulder/thats-an-egg-blog/blob/master/src/pages/index.js#L83 you put your link without http protocol. As it's not an internal link it redirects to a 404 page https://www.thatsanegg.com/www.stormdigital.nl

Suggestion:

```diff
-        <a href="www.stormdigital.nl" target="_blank">
+        <a href="https://www.stormdigital.nl" target="_blank">
```

**Comment by twanmulder** [comment]
Thanks for noticing! I think I missed this somehow :') This is now fixed in [this commit](https://github.com/twanmulder/thats-an-egg-blog/commit/83631e77ce94eb1e3d74cf9d5a49c92e4e2aa800)
